/**
 * Area-related types for organizing todos into logical groups (e.g. Work, Personal).
 */

/** A user-defined area for categorizing todos. */
export interface Area {
  id: number;
  user_id: string;
  name: string;
  /** Material Design hex color (#RRGGBB) used for visual indicators. */
  color: string;
  /** URL-safe slug generated by the backend from the area name. */
  reference_code: string;
  /** Free-text description used by AI categorization to match incoming todos. */
  description: string | null;
  is_default: boolean;
  created_at: string;
  updated_at: string;
}

/** Request body for `POST /areas`. */
export interface CreateAreaRequest {
  name: string;
  color: string;
  description?: string | null;
}

/** Request body for `PUT /areas/:id`. All fields are optional (partial update). */
export interface UpdateAreaRequest {
  name?: string;
  color?: string;
  description?: string | null;
}

/** Area with aggregated todo statistics, returned by `GET /areas/:id/stats`. */
export interface AreaWithStats extends Area {
  stats: {
    total_todos: number;
    completed_todos: number;
    pending_todos: number;
    /** Percentage of completed todos (0-100). */
    completion_rate: number;
  };
}
